name: Deploy
on:
  push:
    branches: [ feat/website ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate config
        run: |
          echo "export const config = { 
            API_KEY: '${{ secrets.API_KEY }}',
            internalARsheetID: '${{ secrets.INTERNALARSHEETID }}'
          };" > src/js/config.js
          echo "js dir:"
          ls src/js
          echo "file content:"
          cat src/js/config.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .